version: '3.8'

services:
  backend:
    build: . 
    ports:
      - '8080:8080'
    environment:
      DATABASE_HOST: db
    depends_on:
      db:
        condition: service_healthy 

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=chirp_user
      - POSTGRES_PASSWORD=chirp_password
      - POSTGRES_DB=chirp_db
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chirp_user -d chirp_db"]
      interval: 10s
      timeout: 5s
      retries: 5